### PR TITLE
Refactor render

### LINKED ISSUE #14: Refactor the 'render' command
Refactor the 'render' command as stated in #4

### PR DESCRIPTION
**Pull request by AbhyudayaSharma**
References #4 
Closes #14

### CODE REVIEW

**Comment by Shynixn** [comment]
Thanks @AbhyudayaSharma for your contribution. This is a valid pull request and can be counted towards Hacktoberfest.

If you have got time, there are some little things need to be adjusted before I can merge it into master:
* Use the interface Plugin instead of JavaPlugin as constructor and field type in your command class
* Move the content from the createRenderCommand to the onPlayerExecuteCommand function and remove the createRenderCommand function.

**Comment by AbhyudayaSharma** [comment]
@Shynixn Thanks for your review. I'll make the changes.

**Comment by AbhyudayaSharma** [comment]
Done! I hope you won't mind if I refactor another of those commands.

**Comment by Shynixn** [comment]
Looks good to me 👍 Sure go ahead but please submit a new issue and pullrequest.

**Pull request merged**
